### ISSUE TITLE
Error while using patchrex in command line mode

### ISSUE THREAD

**Issue by ronakdborad** [shellphish/patcherex#1]
Hi everyone,
I am newbie to patchrex. I am using it for first time.
While running patchrex in command line mode, it stops with import error.
It is:
File "/home/ronak/patchrex/myproj/cgc/patcherex-master/patcherex/backends/reassembler_backend.py", line 7, in <module>
    import compilerex
ImportError: No module named compilerex

Can anyone please help me with it.
Thanks

**Comment by ltfish** [comment]
It's here: https://github.com/mechaphish/compilerex

**Comment by ronakdborad** [comment]
Thanks a lot.
