### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by qiannianshuangxue** [shellphish/patcherex#10]
Could not find a version that satisfies the requirement povsim (from patcherex==1.2) (from versions: )
No matching distribution found for povsim (from patcherex==1.2)

**Comment by zardus** [comment]
We don't offer installation support for the Mechanical Phish components. Check out the `shellphish/mechaphish` docker, where patcherex is already installed. You can look at the source Dockerfile (in github.com/mechaphish/setup) to see how that container is built.

**Comment by qiannianshuangxue** [comment]
Thank you for your answer,How can i build the docker by .gitlab-ci.yml

**Comment by ltfish** [comment]
Also, you don't need to care about `povsim`. You can simply modify `setup.py` of Patcherex and remove the requirement of `povsim`.

**Comment by qiannianshuangxue** [comment]
thank you sir. Now i install it success。
